// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb7bapryX_YOD8FI3wqucyu-L1gkutBgM',
    appId: '1:1078206926626:web:92a2521c0c0474af881f7b',
    messagingSenderId: '1078206926626',
    projectId: 'monterrainci-628b0',
    authDomain: 'monterrainci-628b0.firebaseapp.com',
    storageBucket: 'monterrainci-628b0.firebasestorage.app',
    measurementId: 'G-VQE35061T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASbhAax7Bi2yxk4AlNjtFJsxOM5SYdK1w',
    appId: '1:1078206926626:android:ff3a3f126f27715a881f7b',
    messagingSenderId: '1078206926626',
    projectId: 'monterrainci-628b0',
    storageBucket: 'monterrainci-628b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSaY6HKTWHGBVkZtTmSIwYVYASMKxLcpw',
    appId: '1:1078206926626:ios:48cf8893378089a7881f7b',
    messagingSenderId: '1078206926626',
    projectId: 'monterrainci-628b0',
    storageBucket: 'monterrainci-628b0.firebasestorage.app',
    iosBundleId: 'ci.monterrain.monterrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSaY6HKTWHGBVkZtTmSIwYVYASMKxLcpw',
    appId: '1:1078206926626:ios:48cf8893378089a7881f7b',
    messagingSenderId: '1078206926626',
    projectId: 'monterrainci-628b0',
    storageBucket: 'monterrainci-628b0.firebasestorage.app',
    iosBundleId: 'ci.monterrain.monterrain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb7bapryX_YOD8FI3wqucyu-L1gkutBgM',
    appId: '1:1078206926626:web:fecb66bb88910007881f7b',
    messagingSenderId: '1078206926626',
    projectId: 'monterrainci-628b0',
    authDomain: 'monterrainci-628b0.firebaseapp.com',
    storageBucket: 'monterrainci-628b0.firebasestorage.app',
    measurementId: 'G-8NF6EW5G0L',
  );
}
